apiVersion: v1
entries:
  ping-devops:
  - apiVersion: v2
    appVersion: "2512"
    created: "2026-01-07T13:12:48.108661-08:00"
    description: Ping Identity helm charts - January 6, 2025
    digest: 735bccae3900ad9623a8d09233f5261c17600857171a968d4dae7d081cd9e9cd
    home: https://helm.pingidentity.com/
    icon: https://helm.pingidentity.com/img/logos/ping.png
    name: ping-devops
    type: application
    urls:
    - charts/ping-devops-0.11.16.tgz
    version: 0.11.16
generated: "2026-01-07T13:12:48.105923-08:00"
